# Generated by Django 5.1.2 on 2024-11-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('NbreParticipant', models.IntegerField()),
                ('NbreAchevement', models.IntegerField()),
                ('Type', models.CharField(max_length=200)),
                ('Key', models.CharField(max_length=200)),
            ],
        ),
    ]
