# Generated by Django 5.1.2 on 2024-11-22 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playapp', '0005_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('isvideoMaker', models.BooleanField(default=False)),
                ('videowache', models.IntegerField()),
                ('videowash', models.IntegerField()),
                ('Username', models.CharField(max_length=255, unique=True)),
                ('manysubs', models.IntegerField()),
                ('manyshare', models.IntegerField()),
                ('ApllyForVideoM', models.BooleanField(default=False)),
                ('manyTask', models.IntegerField()),
            ],
        ),
    ]
