# Generated by Django 5.1.2 on 2024-11-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playapp', '0007_userinfo_telephone_userinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='manyTask',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='manyshare',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='manysubs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='videowache',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='videowash',
            field=models.IntegerField(default=0),
        ),
    ]
