# Generated by Django 5.1.2 on 2024-11-28 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playapp', '0008_alter_userinfo_manytask_alter_userinfo_manyshare_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='money',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='userid',
            field=models.IntegerField(default=0, verbose_name=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='userid',
            field=models.IntegerField(default=0),
        ),
    ]
