# Generated by Django 5.1.2 on 2024-12-03 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playapp', '0011_userinteraction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeVideoRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=100, unique=True, verbose_name='ID de la vidéo YouTube')),
                ('video_title', models.CharField(max_length=255, verbose_name='Titre de la vidéo YouTube')),
                ('video_url', models.URLField(max_length=500, verbose_name='Lien de la vidéo YouTube')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure de lecture')),
                ('time_spent', models.DurationField(verbose_name='Temps passé à lire la vidéo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur qui a lu la vidéo')),
            ],
            options={
                'verbose_name': 'Vidéo lue',
                'verbose_name_plural': 'Vidéos lues',
                'ordering': ['-read_at'],
            },
        ),
    ]
