# Generated by Django 5.1.4 on 2024-12-08 03:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playapp', '0012_youtubevideoread'),
    ]

    operations = [
        migrations.CreateModel(
            name='askPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('status', models.CharField(default='', max_length=256)),
            ],
        ),
    ]
