# Generated by Django 5.1.4 on 2024-12-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playapp', '0014_askpay_userid_alter_askpay_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='askpay',
            name='NumeroT',
            field=models.IntegerField(default=0),
        ),
    ]
